# Site settings
title: Rakesh Sripelly
description: A simple blog about me
# baseurl: "/particle" # the subpath of your site, e.g. /blog
# url: "localhost:3000" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Rakesh Sripelly
user_description: Hello! I'm Rakesh Sripelly, Currently working as Software Engineer at Infosys, Hyderabad. I majorly works on Python and Application Development. I feel enthusiastic about open-source contributions, problem-solving, algorithms, love to explore and build real-time applications.
user_title: Technology specialist - Python Infosys, Hyderabad
email: rakeshsripelly490@gmail.com
github_username:  RAKESHSRIPELLY
hackerrank_username: rakeshsripelly41
linkedin_username:  rakesh-sripelly-818093153

Education:
  - course: Bachelor's Degree
    college: Bharath insitute of higher education and research
    percentage: 8.5
    completion: May 2021
  - course: Intermediate, M.P.C
    college: Raos Junior College
    percentage: 90%
    completion: March 2017
  - course: School, S.S.C
    college: Kakatiya Digi School
    percentage: 8.3
    completion: March 2015

Projects:
  - img: /assets/img/classify_binder.jpg
    source_url: https://github.com/VasaviLagishetty/Classify-Binder/
    title: The Classify Binder
    subtitle: File Classification
    description: An application which deals with local file system directories and folders and classifies them into respective folders which makes user task of accessing files easy in that particular directory.
  - img: /assets/img/movie_search.png
    source_url: https://github.com/VasaviLagishetty/MovieSearch
    title: Movie Search
    subtitle: Keyword based search
    description: Developing a React JS application that fetches the data from OMDB API and displays on a web page according to the user search keyword and category.
  - img: /assets/img/covid19.png
    source_url: https://github.com/VasaviLagishetty/COVID19
    title: COVID19 Analysis
    subtitle: Visualizations
    description: A graph plot that describes overall covid19 cases, geographical Visualizations and also top 10 countries with respective confirmed, deaths, recovered cases.
  - img: /assets/img/hcr.png
    source_url: https://code.swecha.org/team2/charrecognition
    title: HCR
    subtitle: Handwritten character recognition
    description: Built a Machine Learning model, Web Application in python to recognize the handwritten digits from images. For future enhancement we will focus on alphabets, numeric data and telugu characters.
  - img: /assets/img/pwa.png
    source_url: https://github.com/VasaviLagishetty/Progressive-Web-App
    title: PWA
    subtitle: Progressive Web Apps
    description: A technical paper presentation on Progressive Web Apps. PWAs are web applications that are regular web pages or websites, but can appear to the user like traditional applications or native mobile applications.
  
social_links:
  - label: My Github
    faicon: github
    url: https://github.com/RAKESHSRIPELLY
  - label: My HackerRank
    faicon: hackerrank
    url: https://www.hackerrank.com/vasavi_2910
  - label: My Linkedin
    faicon: linkedin
    url: https://www.linkedin.com/in/vasavi2910
  - label: My Sourcer
    faicon: chart-line
    url: https://sourcerer.io/vasavilagishetty
  - label: My facebook
    faicon: facebook
    url: https://www.facebook.com/vasavi2910
    
Nav_bar:
  - section: About
    url: /about
  - section: Projects
    url: /projects
  - section: Resume
    url: /about
  - section: Contact
    url: /contact


# Google-analytics
google-analytics:
  id: ""

exclude: ['package.json', 'src' , 'node_modules']
